# Generated by Django 3.1.7 on 2021-03-09 15:24

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyportfolio', '0002_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('jobs_duties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('location', models.CharField(max_length=40)),
                ('technologies', models.CharField(max_length=120)),
            ],
        ),
    ]
