# Generated by Django 3.1.7 on 2021-03-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyportfolio', '0003_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
