# Generated by Django 3.1.7 on 2021-03-09 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyportfolio', '0004_auto_20210309_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='jobs_duties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
