# Generated by Django 3.1.7 on 2021-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyportfolio', '0007_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('Github', models.URLField()),
            ],
        ),
    ]
